version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5499:5432"
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: 'redis:6-alpine'
    command: redis-server
    ports:
      - '6399:6379'
    volumes:
      - 'redis:/data'

  api:
    build: ./blind-test_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3099:3000"
    volumes:
      - ./blind-test_api:/blind-test_api
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  front:
    build: ./blind-test_front
    ports:
      - "8099:8080"
    volumes:
      - ./blind-test_front:/blind-test_front
    depends_on:
      - redis

volumes:
  db:
  redis: